### ISSUE TITLE
I am using Windows play this game, but looks they are Linux code, how really run this on Windows?

### ISSUE THREAD

**Issue by 472516981** [Qemu-Gang/Escape-from-TuxKov#6]
I am using Windows play this game, but looks they are Linux code, how really run this on Windows?

**Comment by LWSS** [comment]
bwana cyka

you cannot run this code on Winblows, you might be able to convert it to another external if u know what you're doing

**Comment by 472516981** [comment]
> 

Possible to use this code  running on Vmware?

**Comment by LWSS** [comment]
like i said u gotta figure that out urself if ur not gonna use linux+qemu
